var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                   oo              x            ",
   "                                                   xx            xx!xx          ",
   "                                            o                    x!!!x          ",
   "                                            x                    xx!xx          ",
   "                                                                  x!x           ",
   "                               o o     o                           v        xx  ",
   "  xx                                  xxx                                    x  ",
   "  x                     o                                                    x  ",
   "  x          xxxx              xxx                                         o x  ",
   "  x          x!!x       o                                          o         x  ",
   "  x  @       x!!x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxx xxxxxx   x!!!!!!!!!!!!!!!!!!x     xxxxxxx   xxxxxxxxx  ",
   "                       x!x    x   x!!!!!!!!!!!!!!!!!!x!!!!!x                    ",
   "                       x!x    x!!!x!!!!!!!!!!!!!!!!!!x!!!!!x                    ",
   "                       x!x    x!!!x!!!!!!!!!!!!!!!!!!x!!!!!x                    ",
   "                       xxx    xxxxx!!!!!!!!!!!!!!!!!!xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                                                                   !!x  ",
   "                                      x!!x                                                                   !!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                !!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx    ooo                        !!x  ",
   "                                       xxxxxxxxxx!!x         x                                      o        !!x  ",
   "                                                xx!x         x     o   o                                    !!!x  ",
   "                                                 x!x         x                               xxxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x        x     x      !!!!!!!!!!!!!!!!!xx  ",
   "                               xxxxxxx                       xxx | x | x |xxxx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                 !!!                          xx!!!!!!!!!!!xx                                     ",
   "                                  v                             !!!!!!!!!!!                                       ",
   "                                                                                 xxx         xxx                  ",
   "                                                                                   x    x    x                    ",
   "     @                            o                                                x         x                    ",
   "    xxx           o                              o                                 x x     x x                    ",
   "    x!x                                          x                                 x    o    x                    ",
   "    x!x                                                              x   x         x    x    x                    ",
   "    x!x                       xxx   xxx              xxxx            !   !         x         x                    ",
   "    x!x                         x   x            o         xxxxxx    !   !   xx    xx        x                    ",
   "    x!x      xx       xx        x   x            x                   !   !   x               x                    ",
   "    x!x      xvvvvvvvvvx   x    x   x                                !   xxxxx          x    x                    ",
   "    x!x      x         x        x   x                                x                       x                    ",
   "    x!x      x         x       ox o xx                               x     o           xxx   x                    ",
   "!!!!x!x!!!!!!x         x!!!!!xxx     xx!!!!!!!!xx    xx!!!!!!!!!     x     =                 x                    ",
   "!!!!x!x!!!!!!x         x!!!!!xxx     Xxxxxxxxxxx     xx!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x!x!!!!!!x         x!!!!!                       xxx!!!!!xx !                    xx     xx                     ",
   "!!!!x!x!!!!!!x         x!!!!! o                    xxxx!!!!xx  !                     xxxxxxx                      ",
   "!!!!x!x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x!x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x!x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x!x                 !!!        !!!  xxxx                        x!!!!!x",
   "                                       x!x                 !!!        !!!                                !!!  ",
   "                                     xxx!xxx                !    oo    !          o                       v   ",
   "                                        v                   !   oooo   !         xxx                          ",
   "                                                            !  xxxxxx  !       xx!!!xx                        ",
   "                                      o                     !!!!!!!!!!!!                                      ",
   "                                     xx   xx         ===        xxxx         o                                ",
   "                                                                            xxx                               ",
   "     =                                           =    !                   xx!!!xx                             ",
   "                                          o           !                                                       ",
   "                                     xx   xx          !             o                                         ",
   "                                                      !            xxx                                        ",
   "     =                                           =    !          xx!!!xx      o                               ",
   "                                      o               !     o       v        xxx                              ",
   "                                     xx   xx          !                    xx!!!xx       o                    ",
   "                                                      !    xxx                v         xxx                   ",
   "                                                      != = = = = = = x                xx!!!xx                 ",
   "                             xxx xxx xxx xxx     o o  !!!!!!!!!!!!!!!x                   v                    ",
   "                             x=           =x          !!!!!!!!!!!!!!!x                                        ",
   "                            xx             x   xxxxxxx!!!!!!!!!!!!!!!x                o                       ",
   "                                          xx                                         xxx                  o   ",
   "  xxx                                     x                   =                    xx   xx               xxx  ",
   "  x x                 xxxxx        xxx    x                                                              x!x  ",
   "  x                                       !xxxxxx                        xxxxx                  xxx!  =   !x  ",
   "  x                                       x                              x = x                            vx  ",
   "  x                           xxxx                  oo        oo         x!!!x                            vx  ",
   "  x                                               |xxxx|    |xxxx|     xx!!!xx                             x  ",
   "  x                                o o                                   !         xxx           o         x  ",
   "  x              o            xxxx     xxxx                             x!x      xx!!!xx         x         x  ",
   "  x              x            x=   xxx  = x                             x!x        v v          x!x        x  ",
   "  x             !!!           !!!!!!!!!!!!!  x oo x  = x oo x =  x oo  xx!xx        v           x!x        x  ",
   "  x      @     !!!!!          !!!!!!!!!!!!!xxx    x!!!!x    x!!!!x    xx!!!xx                    !         x  ",
   "  xxxxxxxxxxxx!!!!!!!xxxxxxxxxx!!!!!!!!!!!xxxxxxxxx!!!!xxxxxx!!!!xxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
